usb: avoid k_yield in usb_write when called from ISR
Logitech/scbg-zephyr pull request #21
Opened 2022-01-24 22:51 UTC by somagriff

When usb_dc_ep_write fails in usb_write with EAGAIN, the code was logging
and retrying via k_yield. It seems this function can be called both from
the context of a thread or from an ISR. When called from an ISR we cannot
call k_yield, which in our implementation was causing an assertion,
kernel panic and halt.

Only yield back if we're not in an ISR, otherwise exit immediately with
EAGAIN without retry, and let the caller handle it.

Change the LOG to a printk to avoid similar ISR context issues seen
during logging, whilst still maintaining the log print for completeness.

Signed-off-by: Andy Griffin <agriffin@logitech.com>

2022-01-24 23:04 UTC, salggarcia reviewed
Tried this a couple times but can't get it to get to this point (usb write fail), but this does seem safer than what it was doing

2022-01-24 23:10 UTC, somagriff commented
I can provoke this fairly reliably by just unplugging and replugging whilst enumerated on my mac.

2022-01-24 23:18 UTC, salggarcia commented
Ok I was able to get it without this fix (and thus crash), but now with this fix it does not crash!

2022-01-24 23:37 UTC, nickstoughton commented
Please run `gitlint` on such commits. The first line is too long.

2022-01-24 23:41 UTC, nickstoughton requested changes

2022-01-24 23:41 UTC, nickstoughton commented on subsys/usb/usb_device.c
> +			printk("Failed to write endpoint buffer 0x%02x", ep);
We should not be using either `printk` nor `LOG_WRN`. Logging is marginally better than `printk`, but there will be an error message even without this (on before, from `usb_dc_ep_write` and one afterwards from `SendCSW`) and it does nothing but clutter up the output. The error will be clearer without this.

2022-01-25 00:01 UTC, somagriff commented on subsys/usb/usb_device.c
> +			printk("Failed to write endpoint buffer 0x%02x", ep);
"We" are not using, this is upstream code being called in multiple contexts. Can't say I agree with logging an error like this as being clutter -- that should be solved by setting log-level, and remember the msc code is not the only caller of this. So yes, changing to printk would change behavior for all, and if leaving it as LOG means we might still assert, then yes we can avoid the situation by not printing here, but be aware that if the concern is for being an ISR context callee from msc.c that there are numerous functions in the path to get here that also LOG.

But wanting to oil the wheels, so have changed it.

2022-01-25 00:02 UTC, somagriff commented on subsys/usb/usb_device.c
> +			printk("Failed to write endpoint buffer 0x%02x", ep);
Have run gitlint... had checked this in my editor, but accidentally had it set to 73.

2022-01-25 00:13 UTC, nickstoughton approved these changes

2022-01-25 00:21 UTC, somagriff commented
Following further discussion, reworked to use the original strategy of `break`ing, whilst also removing the contentious log message completely.

2022-01-25 15:56 UTC, nickstoughton requested changes

2022-01-25 16:12 UTC, somagriff commented on kernel/timer.c
> +		/* Unlock for user handler. */
OK, rebased to restore this.

2022-01-25 16:17 UTC, nickstoughton approved these changes

2022-01-25 16:48 UTC, merged