usb/dfu: prepare forwarding images to other mcus (V2)
Logitech/scbg-zephyr pull request #9
Opened 2021-08-30 14:30 UTC by djcb

This lays the foundation for forwarding DFU images to other MCUs.

1. We scan the first packet to find out the kind of image, which is encoded
   in the LSB of the build-id (using the mcuboot boot header), in `dfu_probe()`
2. Now, either flash the image locallly, or transfer it:
  a) If we find that it's a local image, we use `dfu_flash_write()` (unchanged)
	to flash it in the usual way
  b) If we find it's a xeno-image for _another_ MCU, we send it there over the UART, 
       using mcumgr/SMP. TBI (future PR). `dfu_forward_write()`

Packets can be concatenated, so we keep track of how much data has been written. once an image has be been fully written (using either (2a) or (2b)), we go back to (1).

Since we now do everything in mcuboot, we can remove the status/write callbacks added earlier.

Changes since V1:
- image-detection and mcumgr-forwarding are not Stradale specific, so we refactored that part
- added files `usb_dfu_mcumgr.[ch]` which define/implement `dfu_probe_kind`, which probe the kind of image we're seeing, in terms of the target MCU and whether it's local or remote
- the actual detection / naming is "topology-specific", so every topology/setup can decide on how to determine the mcus basic on an image-header
- implement a Kconfig choice (predicated on `CONFIG_USB_DFU_FORWARD`) and implementation for the default topology `USB_DFU_FORWARD_TOPOLOGY_NONE`) which makes DFU "multi image aware" but flashes locally, and `USB_DFU_FORWARD_TOPOLOGY_STRADALE`) which implements Stradale-specific MCU-detection / naming etc.
- WIthout  `CONFIG_USB_DFU_FORWARD` you get the unsullied Zephyr DFU/USB codepaths. 

Note: the `CONFIG_USB_DFU_FORWARD` blob is still in `usb_dfu.c`; it could _potentially_ go to `usb_dfu_mcumgr.c` as well, with a bit churn since it needs access to some of the `usb_dfu.c` internals. In any case, I could do that later, as part of the actual mcumgr client code, which will also go to `usb_dfu_mcumgr.c`

2021-08-30 14:42 UTC, nickstoughton requested changes

2021-08-30 14:42 UTC, nickstoughton commented on subsys/usb/class/dfu/usb_dfu.c
> +	switch(dfu_dispatch.img_kind) {
This appears to be extremely Stradale-specific. It would be good to keep the kernel clean and have Stradale-specific stuff handled via a callback or similar. Or maybe a "this CPU"/"Other CPU" (rather than STM/nRF) or even CPU0, CPU1, CPU2 etc, where 0 is always "this". But ask @somagriff  as well ... I trust his instincts here.

2021-08-30 14:42 UTC, nickstoughton commented on subsys/usb/class/dfu/usb_dfu.c
> +
multi-line white-space

2021-08-30 15:10 UTC, djcb commented on subsys/usb/class/dfu/usb_dfu.c
> +	switch(dfu_dispatch.img_kind) {
Well, we have to have the stradale stuff _somewhere_, and it needs to do what we're doing here. 

Right now, all our stradale-specific stuff is in the `CONFIG_USB_DFU_FORWARD` block, but it needs access to some of the internals of usb_dfu. 

So I can ask abstract it to, say, `usb_dfu_fwd_stradale.c` but if you want to have something that is a general solution to the problem of forwarding MCU images... that's a bit more work. At best we can do _a little bit_ .

2021-08-30 15:13 UTC, djcb commented on subsys/usb/class/dfu/usb_dfu.c
> +
The horror! :) FIxed.

2021-08-31 07:29 UTC, djcb commented
I'll mark it as _draft_ for now, and refactor it a bit.

2021-08-31 13:12 UTC, nickstoughton commented on subsys/usb/class/dfu/usb_dfu_stradale.c
> +	};
The "real" Zephyr would want to get this information from a user application, perhaps via a `register_topology` API or similar. Topologies might also want some form of identifier for the transport to remote MCUs, e.g. `UART0` or `SPI1-0` or similar.

And they might even want to use something like Open-AMP for IPC. But that really would be building a tank to crack an egg :-)

2021-08-31 13:12 UTC, nickstoughton commented on subsys/usb/class/dfu/usb_dfu_mcumgr.h
> +};
see below for transport idea.

2021-08-31 13:42 UTC, djcb commented on subsys/usb/class/dfu/usb_dfu.c
> + * 2. Now, either flash the image locallly, or transfer it:
Fixed.

2021-08-31 13:46 UTC, djcb commented on subsys/usb/class/dfu/usb_dfu_stradale.c
> +	};
I think you should not see this as app-code invading Zephyr, but as a "Stradale DFU Driver"; drivers tend to have hardware-specific details. The

(note there _is_ no  user-application here; this runs as part of mcuboot)

2021-08-31 14:03 UTC, djcb commented on subsys/usb/class/dfu/usb_dfu_stradale.c
> +	};
For the transport to the remote, that's determined already: `zephyr,uart-mcumgr` in the DTS

2021-08-31 16:04 UTC, nickstoughton approved these changes

2021-08-31 16:04 UTC, merged